version: "3"

services:
 shops-service:
  image: hmisra/shops:v2
  container_name: shops
  build: .
  ports:
   - 8083:8083
  links:
   - demo-service
   - customer-service
 demo-service:
  image: hmisra/demo:v1
  container_name: demo
  ports:
   - 8081:8081
 customer-service:
  image: hmisra/customer-api:v1
  container_name: customers
  ports:
  - 8082:8082
  links:
   - mongo
 mongo:
  image: mongo
  container_name: customers-mongo
  ports:
   - 27017:27017
 # volumes are not working for windows for docker. Hence commenting. Need to uncomment for linux
 # volumes:
 #  - ./data/db:/data/db