version: "3"

services:
 shops-service:
  image: hmisra/shops:v2
  container_name: shops
  build: .
  ports:
   - 8083:8083
  depends_on: #links does not wwork in version 3 and swarm and stacks so using depends on
   - demo-service
   - customer-service
  networks:
   - my-network
 demo-service:
  image: hmisra/demo:v1
  container_name: demo
  ports:
   - 8081:8081
 customer-service:
  image: hmisra/customer-api:v2
  container_name: customers
  deploy:
    mode: replicated
    replicas: 2
  ports:
  - 8082:8082
  depends_on:
   - mongo
  networks:
   - my-network
 mongo:
  image: mongo:3.2.4
  container_name: customers-mongo
  ports:
   - 27017:27017
 # volumes are not working for windows for docker. Hence commenting. Need to uncomment for linux
 # volumes:
 #  - ./data/db:/data/db
  networks:
   - my-network
networks:
  my-network:
   driver: overlay