version: "3"

services:
 shops-service:
  container_name: shops
  build: .
  ports:
   - 8083:8083
  links:
   - demo-service
   - customer-service
 demo-service:
  image: hmisra/demo:v1
  container_name: demo
  ports:
   - 8081:8081
 customer-service:
  image: hmisra/customer-api:v1
  container_name: customers
  ports:
  - 8082:8082